#!/bin/zsh

rm -fr cscope.*

find `pwd` -iname "*.go"	>cscope.files
find `pwd` -iname "*.goc"	>>cscope.files
find `pwd` -iname "*.[chs]"	>>cscope.files
find `pwd` -iname "*.cpp"	>>cscope.files

cscope -bq
