# No syntax highlight color scheme
colorscheme nofrils-acme
# Show absolute line number by default
add-highlighter global/number-lines number-lines -hlcursor -separator ' '
hook global WinCreate [^*].* %{
    # Show relative line number for main client
    add-highlighter window/number-lines number-lines -relative -hlcursor -separator ' '
    # Highlight trailing space
    add-highlighter window/space regex \h+$ 0:default,magenta
}
# Show matching paris
add-highlighter global/show-matching show-matching
# Wrap on word boundary
add-highlighter global/wrap wrap -word -indent -marker "↳ "
# The width of a tab is 4 spaces by default
set-option global tabstop 4
# Indent with a tab
set-option global indentwidth 0
# Make current line in the middle of screen
set-option global scrolloff 37,0
# Status line
set-option global modelinefmt '%val{bufname} %val{cursor_line}/%val{buf_line_count}:%val{cursor_char_column} {{context_info}} {{mode_info}} - %val{client}@[%val{session}]'
# Shortcut to edit kakrc
define-command kakrc -docstring "Edit kakrc" %{
    edit "%val{config}/kakrc"
}
# User mappings
map -docstring "write" global user w ': w<ret>'
map -docstring "quit" global user q ': q<ret>'
# Pathogen proliferation
source "%val{config}/pathogen/pathogen.kak"
# Echo mode
pathogen-infect "%val{config}/echo"
# Sudo write
pathogen-infect "%val{config}/sudo"
# Readline shortcuts in insert mode
pathogen-infect "%val{config}/readline"
# Comment mode
pathogen-infect "%val{config}/comment"
# Search
pathogen-infect "%val{config}/search"
# Kak-lsp
pathogen-infect "%val{config}/kak-lsp"
# Clipboard
pathogen-infect "%val{config}/clipboard"
# Current line/column highlight
pathogen-infect "%val{config}/kak-crosshairs"
cursorline
# fzf for files and searches
pathogen-infect "%val{config}/fzf"

define-command -hidden grep_from_top %{
	execute-keys %sh{
		topdir() {
	        dirname_buffer="${kak_buffile%/*}"
	        if [ "${dirname_buffer}" = "${kak_buffile}" ]; then
	            printf 'fail grep_from_top: cannot operate on scratch buffer: %s\n' "${kak_buffile}"
	            return 1
	        fi
	        cd "${dirname_buffer}" 2>/dev/null || {
	            printf 'fail grep_from_top: unable to change the current working directory to: %s\n' "${dirname_buffer}"
	            return 1
	        }
	        git_topdir="$(git rev-parse --show-toplevel)"
	        if [ "${git_topdir}" != "${HOME}" ]; then
	        	printf "%s" "$(realpath ${git_topdir})"
        	else
	        	printf "%s" "$(realpath ${dirname_buffer})"
	        fi
	    }
		printf ":grep -I -w %s %s<ret>" "${kak_selection}" "$(topdir)"
	}
}
map global user g "<a-i>w:grep_from_top<ret>" -docstring 'grep word at current cursor'
