# Show relative line number
add-highlighter global/number-lines number-lines -relative -hlcursor -separator ' '
# Show matching paris
add-highlighter global/show-matching show-matching
# Wrap on word boundary
add-highlighter global/wrap wrap -word -indent -marker "↳ "
# Tabs using 4 spaces by default
set-option global tabstop 4
# Status line
set-option global modelinefmt '%val{bufname} %val{cursor_line}/%val{buf_line_count}:%val{cursor_char_column} {{context_info}} {{mode_info}} - %val{client}@[%val{session}]'
# Shortcut to edit kakrc
define-command kakrc -docstring "Edit kakrc" %{
    edit "%val{config}/kakrc"
}
# Mimic vim's '#' key
map -docstring "search word under current cursor" global normal <#> <a-i>w*n
# Clear current search register
map -docstring "clear current search register" global user <space> ": reg '/' ''<ret>"
# User mappings
map -docstring "write" global user w ': w<ret>'
# Highlight current search content
add-highlighter global/ dynregex '%reg{/}' 0:default,+u
# Pathogen proliferation
source "%val{config}/pathogen/pathogen.kak"
# Define ide command for basic IDE layout
pathogen-infect "%val{config}/ide"
# Echo mode
pathogen-infect "%val{config}/echo"
# Sudo write
pathogen-infect "%val{config}/sudo"
# Gtag mode
pathogen-infect "%val{config}/gtag"
# Show difference between buf and file
pathogen-infect "%val{config}/diff"
# Readline shortcuts in insert mode
pathogen-infect "%val{config}/readline"
# Comment mode
pathogen-infect "%val{config}/comment"
# Focus mode
pathogen-infect "%val{config}/focus"
# youdao-translation
pathogen-infect "%val{config}/youdao"
# Golang
pathogen-infect "%val{config}/go"
# Makefile mode
pathogen-infect "%val{config}/make"
