# No syntax highlight color scheme
colorscheme nofrils-acme
# Show absolute line number by default
add-highlighter global/number-lines number-lines -hlcursor -separator ' '
hook global WinCreate [^*].* %{
    # Show relative line number for main client
    add-highlighter window/number-lines number-lines -relative -hlcursor -separator ' '
    # Highlight trailing space
    add-highlighter window/space regex \h+$ 0:default,magenta
}
# Show matching paris
add-highlighter global/show-matching show-matching
# Wrap on word boundary
add-highlighter global/wrap wrap -word -indent -marker "↳ "
# The width of a tab is 4 spaces by default
set-option global tabstop 4
# Indent with a tab
set-option global indentwidth 0
# Status line
set-option global modelinefmt '%val{bufname} %val{cursor_line}/%val{buf_line_count}:%val{cursor_char_column} {{context_info}} {{mode_info}} - %val{client}@[%val{session}]'
# Shortcut to edit kakrc
define-command kakrc -docstring "Edit kakrc" %{
    edit "%val{config}/kakrc"
}
# User mappings
map -docstring "write" global user w ': w<ret>'
map -docstring "quit" global user q ': q<ret>'
# Pathogen proliferation
source "%val{config}/pathogen/pathogen.kak"
# Define ide command for basic IDE layout
pathogen-infect "%val{config}/ide"
# Echo mode
pathogen-infect "%val{config}/echo"
# Sudo write
pathogen-infect "%val{config}/sudo"
# Gtag mode
pathogen-infect "%val{config}/gtag"
# Show difference between buf and file
pathogen-infect "%val{config}/diff"
# Readline shortcuts in insert mode
pathogen-infect "%val{config}/readline"
# Comment mode
pathogen-infect "%val{config}/comment"
# Focus mode
pathogen-infect "%val{config}/focus"
# youdao-translation
pathogen-infect "%val{config}/youdao"
# Golang
pathogen-infect "%val{config}/go"
# Makefile mode
pathogen-infect "%val{config}/make"
# Tool client jump
pathogen-infect "%val{config}/tj"
# Notmuch
pathogen-infect "%val{config}/notmuch"
# Search
pathogen-infect "%val{config}/search"
# Kak-lsp
pathogen-infect "%val{config}/kak-lsp"
