---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      parts:
        - direction: Horizontal
          borderless: true
          split_size:
            Percent: 70
          run:
            plugin:
              location: "zellij:tab-bar"
        - direction: Horizontal
          borderless: true
          split_size:
            Percent: 30
          run:
            plugin:
              location: "file:/home/tw/.cargo/bin/pomodoro-clock.wasm"
              _allow_exec_host_cmd: true

tabs:
  - direction: Vertical