---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          path: tab-bar
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      parts:
        - direction: Horizontal
          borderless: true
          split_size:
            Percent: 70
          run:
            plugin:
              path: status-bar
        - direction: Horizontal
          borderless: true
          split_size:
            Percent: 30
          run:
            plugin:
              path: /home/tw/code/zellij-pomodoro-plugin/target/wasm32-wasi/debug/zellij-pomodoro-plugin.wasm
              _allow_exec_host_cmd: true

tabs:
  - direction: Vertical