simplified_ui: true
default_shell: "/home/tw/.cargo/bin/nu"

keybinds:
  unbind: [ Ctrl: 'r']
  normal:
    - action: [ GoToTab: 1,]
      key: [ Alt: '1',]
    - action: [ GoToTab: 2,]
      key: [ Alt: '2',]
    - action: [ GoToTab: 3,]
      key: [ Alt: '3',]
    - action: [ GoToTab: 4,]
      key: [ Alt: '4',]
    - action: [ GoToTab: 5,]
      key: [ Alt: '5',]
    - action: [ GoToTab: 6,]
      key: [ Alt: '6',]
    - action: [ GoToTab: 7,]
      key: [ Alt: '7',]
    - action: [ GoToTab: 8,]
      key: [ Alt: '8',]
    - action: [ GoToTab: 9,]
      key: [ Alt: '9',]

themes:
  default:
    fg: [128, 128, 128]
    bg: [0xff,0xff,0xd7]
    black: [0,0,0]
    red: [222, 29, 16]
    green: [71, 166, 31]
    yellow: [0,0,0]
    blue: [0,0,0xff]
    magenta: [0,0,0]
    cyan: [0xff,0xff,0xd7]
    white: [0,0,0]
    orange: [0,0,0]