[user]
name = "Tw"
email = "tw19881113@gmail.com"

[ui]
diff.format = "git"
default-command = "log"

[fix.tools.clang-format]
command = ["clang-format", "--assume-filename=$path"]
patterns = ["glob:'**/*.cc'",
            "glob:'**/*.c'",
            "glob:'**/*.h'"]

[fix.tools.zigfmt]
command = ["zig", "fmt", "--stdin"]
patterns = ["glob:'**/*.zig'"]

[templates]
commit_trailers = '''
format_signed_off_by_trailer(self)
++ if(!trailers.contains_key("Change-Id"), format_gerrit_change_id_trailer(self))'''
