[user]
name = "Tw"
email = "tw19881113@gmail.com"

[ui]
diff.format = "git"
default-command = "log"

[fix.tools.clang-format]
command = ["clang-format", "--assume-filename=$path"]
patterns = ["glob:'**/*.cc'",
            "glob:'**/*.c'",
            "glob:'**/*.h'"]

[fix.tools.zigfmt]
command = ["zig", "fmt", "--stdin"]
patterns = ["glob:'**/*.zig'"]

[template-aliases]
_signed_off = '''
if(!description.contains("Signed-off-by: "),
  concat(
    "\nSigned-off-by: ",
    author.name(),
    surround(" <", ">", author.email()),
  )
)
'''
_change_id = '''
if(!description.contains("Change-Id: I"),
  "\nChange-Id: I00000000" ++ change_id.normal_hex()
)
'''
